-- 达梦 8 初始化脚本。建议使用独立模式/用户执行，不要直接在业务共享模式中运行。

CREATE TABLE PT_TAG_DEFINITION (
    ID VARCHAR(32) NOT NULL,
    CODE VARCHAR(64) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    STATUS INT DEFAULT 1 NOT NULL,
    AUTO_APPROVE INT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_TAG_DEFINITION PRIMARY KEY (ID),
    CONSTRAINT UK_PT_TAG_DEFINITION_CODE UNIQUE (CODE)
);

COMMENT ON TABLE PT_TAG_DEFINITION IS '标签定义表';
COMMENT ON COLUMN PT_TAG_DEFINITION.ID IS '标签主键，32位UUID';
COMMENT ON COLUMN PT_TAG_DEFINITION.CODE IS '标签业务编码，对接外部系统且全局唯一';
COMMENT ON COLUMN PT_TAG_DEFINITION.NAME IS '标签名称';
COMMENT ON COLUMN PT_TAG_DEFINITION.CATEGORY IS '标签分类';
COMMENT ON COLUMN PT_TAG_DEFINITION.DESCRIPTION IS '标签说明';
COMMENT ON COLUMN PT_TAG_DEFINITION.STATUS IS '启用状态：1启用，0停用';
COMMENT ON COLUMN PT_TAG_DEFINITION.AUTO_APPROVE IS '规则命中后是否自动通过：1是，0否';
COMMENT ON COLUMN PT_TAG_DEFINITION.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_TAG_DEFINITION.UPDATED_AT IS '更新时间';

CREATE TABLE PT_TAG_RULE (
    ID VARCHAR(32) NOT NULL,
    TAG_ID VARCHAR(32) NOT NULL,
    KEYWORD VARCHAR(200) NOT NULL,
    NORMALIZED_KEYWORD VARCHAR(200) NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    VERSION_NO INT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_TAG_RULE PRIMARY KEY (ID),
    CONSTRAINT FK_PT_TAG_RULE_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_PT_TAG_RULE_WORD UNIQUE (TAG_ID, NORMALIZED_KEYWORD)
);

COMMENT ON TABLE PT_TAG_RULE IS '标签关键词规则表';
COMMENT ON COLUMN PT_TAG_RULE.ID IS '规则主键，32位UUID';
COMMENT ON COLUMN PT_TAG_RULE.TAG_ID IS '关联标签主键';
COMMENT ON COLUMN PT_TAG_RULE.KEYWORD IS '原始匹配关键词';
COMMENT ON COLUMN PT_TAG_RULE.NORMALIZED_KEYWORD IS '标准化后的匹配关键词';
COMMENT ON COLUMN PT_TAG_RULE.STATUS IS '启用状态：1启用，0停用';
COMMENT ON COLUMN PT_TAG_RULE.VERSION_NO IS '规则版本号，每次状态变更递增';
COMMENT ON COLUMN PT_TAG_RULE.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_TAG_RULE.UPDATED_AT IS '更新时间';

CREATE TABLE PT_PERSON (
    ID VARCHAR(32) NOT NULL,
    EXTERNAL_ID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(20),
    ORGANIZATION VARCHAR(200),
    OCCUPATION VARCHAR(200),
    ADDRESS VARCHAR(500),
    REMARK VARCHAR(1000),
    SOURCE_UPDATED_AT TIMESTAMP,
    DELETED_FLAG INT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_PERSON PRIMARY KEY (ID),
    CONSTRAINT UK_PT_PERSON_EXTERNAL_ID UNIQUE (EXTERNAL_ID)
);

COMMENT ON TABLE PT_PERSON IS '人员基础资料表';
COMMENT ON COLUMN PT_PERSON.ID IS '人员主键，32位UUID';
COMMENT ON COLUMN PT_PERSON.EXTERNAL_ID IS '上游人员唯一编码';
COMMENT ON COLUMN PT_PERSON.NAME IS '人员姓名';
COMMENT ON COLUMN PT_PERSON.GENDER IS '性别';
COMMENT ON COLUMN PT_PERSON.ORGANIZATION IS '所属机构';
COMMENT ON COLUMN PT_PERSON.OCCUPATION IS '职业';
COMMENT ON COLUMN PT_PERSON.ADDRESS IS '地区或地址';
COMMENT ON COLUMN PT_PERSON.REMARK IS '人员备注';
COMMENT ON COLUMN PT_PERSON.SOURCE_UPDATED_AT IS '上游数据更新时间，用于防止旧数据覆盖';
COMMENT ON COLUMN PT_PERSON.DELETED_FLAG IS '逻辑删除标志：1已删除，0正常';
COMMENT ON COLUMN PT_PERSON.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_PERSON.UPDATED_AT IS '更新时间';

CREATE TABLE PT_PERSON_TAG (
    ID VARCHAR(32) NOT NULL,
    PERSON_ID VARCHAR(32) NOT NULL,
    TAG_ID VARCHAR(32) NOT NULL,
    SOURCE_TYPE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    RULE_ID VARCHAR(32),
    BATCH_NO VARCHAR(100),
    MATCHED_KEYWORD VARCHAR(200),
    REVIEWED_BY VARCHAR(100),
    REVIEWED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_PERSON_TAG PRIMARY KEY (ID),
    CONSTRAINT FK_PT_PERSON_TAG_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PT_PERSON(ID),
    CONSTRAINT FK_PT_PERSON_TAG_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_PT_PERSON_TAG UNIQUE (PERSON_ID, TAG_ID)
);

COMMENT ON TABLE PT_PERSON_TAG IS '人员标签关系表';
COMMENT ON COLUMN PT_PERSON_TAG.ID IS '人员标签关系主键，32位UUID';
COMMENT ON COLUMN PT_PERSON_TAG.PERSON_ID IS '关联人员主键';
COMMENT ON COLUMN PT_PERSON_TAG.TAG_ID IS '关联标签主键';
COMMENT ON COLUMN PT_PERSON_TAG.SOURCE_TYPE IS '标签来源：MANUAL人工、REMOTE上游、RULE规则';
COMMENT ON COLUMN PT_PERSON_TAG.STATUS IS '审核状态：PENDING待审核、APPROVED已通过、REJECTED已拒绝';
COMMENT ON COLUMN PT_PERSON_TAG.RULE_ID IS '命中的规则主键，仅规则标签使用';
COMMENT ON COLUMN PT_PERSON_TAG.BATCH_NO IS '产生或更新该关系的同步批次号';
COMMENT ON COLUMN PT_PERSON_TAG.MATCHED_KEYWORD IS '规则匹配到的关键词';
COMMENT ON COLUMN PT_PERSON_TAG.REVIEWED_BY IS '审核人或人工操作人';
COMMENT ON COLUMN PT_PERSON_TAG.REVIEWED_AT IS '审核时间';
COMMENT ON COLUMN PT_PERSON_TAG.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_PERSON_TAG.UPDATED_AT IS '更新时间';

CREATE TABLE PT_SYNC_BATCH (
    ID VARCHAR(32) NOT NULL,
    BATCH_NO VARCHAR(100) NOT NULL,
    SYNC_TYPE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CURSOR_BEFORE VARCHAR(500),
    CURSOR_AFTER VARCHAR(500),
    RECEIVED_COUNT INT DEFAULT 0 NOT NULL,
    SUCCESS_COUNT INT DEFAULT 0 NOT NULL,
    FAILURE_COUNT INT DEFAULT 0 NOT NULL,
    ERROR_MESSAGE VARCHAR(1000),
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    CONSTRAINT PK_PT_SYNC_BATCH PRIMARY KEY (ID),
    CONSTRAINT UK_PT_SYNC_BATCH_NO UNIQUE (BATCH_NO)
);

COMMENT ON TABLE PT_SYNC_BATCH IS '人员同步批次记录表';
COMMENT ON COLUMN PT_SYNC_BATCH.ID IS '同步批次主键，32位UUID';
COMMENT ON COLUMN PT_SYNC_BATCH.BATCH_NO IS '同步批次号，调度重试幂等键';
COMMENT ON COLUMN PT_SYNC_BATCH.SYNC_TYPE IS '同步类型，当前为INCREMENTAL增量同步';
COMMENT ON COLUMN PT_SYNC_BATCH.STATUS IS '执行状态：RUNNING执行中、SUCCESS成功、FAILED失败';
COMMENT ON COLUMN PT_SYNC_BATCH.CURSOR_BEFORE IS '本批次开始前的增量游标';
COMMENT ON COLUMN PT_SYNC_BATCH.CURSOR_AFTER IS '本批次处理后的增量游标';
COMMENT ON COLUMN PT_SYNC_BATCH.RECEIVED_COUNT IS '从上游接收的记录数';
COMMENT ON COLUMN PT_SYNC_BATCH.SUCCESS_COUNT IS '处理成功记录数';
COMMENT ON COLUMN PT_SYNC_BATCH.FAILURE_COUNT IS '处理失败记录数';
COMMENT ON COLUMN PT_SYNC_BATCH.ERROR_MESSAGE IS '批次失败原因';
COMMENT ON COLUMN PT_SYNC_BATCH.STARTED_AT IS '开始时间';
COMMENT ON COLUMN PT_SYNC_BATCH.FINISHED_AT IS '结束时间';

CREATE TABLE PT_SYNC_STATE (
    TASK_CODE VARCHAR(64) NOT NULL,
    LAST_CURSOR VARCHAR(500),
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_SYNC_STATE PRIMARY KEY (TASK_CODE)
);

COMMENT ON TABLE PT_SYNC_STATE IS '同步任务游标状态表';
COMMENT ON COLUMN PT_SYNC_STATE.TASK_CODE IS '同步任务编码';
COMMENT ON COLUMN PT_SYNC_STATE.LAST_CURSOR IS '最近成功提交的增量游标';
COMMENT ON COLUMN PT_SYNC_STATE.UPDATED_AT IS '游标更新时间';

CREATE INDEX IDX_PT_RULE_TAG_STATUS ON PT_TAG_RULE(TAG_ID, STATUS);
CREATE INDEX IDX_PT_PERSON_NAME ON PT_PERSON(NAME);
CREATE INDEX IDX_PT_PERSON_TAG_TAG ON PT_PERSON_TAG(TAG_ID, STATUS, PERSON_ID);
CREATE INDEX IDX_PT_PERSON_TAG_PERSON ON PT_PERSON_TAG(PERSON_ID, STATUS);
CREATE INDEX IDX_PT_BATCH_STATUS ON PT_SYNC_BATCH(STATUS, STARTED_AT);

INSERT INTO PT_SYNC_STATE(TASK_CODE, LAST_CURSOR, UPDATED_AT)
VALUES ('PERSON_INCREMENTAL', NULL, CURRENT_TIMESTAMP);
