-- 达梦 8 初始化脚本。建议使用独立模式/用户执行，不要直接在业务共享模式中运行。

CREATE TABLE PT_TAG_DEFINITION (
    ID VARCHAR(32) NOT NULL,
    CODE VARCHAR(64) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    STATUS INT DEFAULT 1 NOT NULL,
    AUTO_APPROVE INT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_TAG_DEFINITION PRIMARY KEY (ID),
    CONSTRAINT UK_PT_TAG_DEFINITION_CODE UNIQUE (CODE)
);

CREATE TABLE PT_TAG_RULE (
    ID VARCHAR(32) NOT NULL,
    TAG_ID VARCHAR(32) NOT NULL,
    KEYWORD VARCHAR(200) NOT NULL,
    NORMALIZED_KEYWORD VARCHAR(200) NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    VERSION_NO INT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_TAG_RULE PRIMARY KEY (ID),
    CONSTRAINT FK_PT_TAG_RULE_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_PT_TAG_RULE_WORD UNIQUE (TAG_ID, NORMALIZED_KEYWORD)
);

CREATE TABLE PT_PERSON (
    ID VARCHAR(32) NOT NULL,
    EXTERNAL_ID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(20),
    ORGANIZATION VARCHAR(200),
    OCCUPATION VARCHAR(200),
    ADDRESS VARCHAR(500),
    REMARK VARCHAR(1000),
    SOURCE_UPDATED_AT TIMESTAMP,
    DELETED_FLAG INT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_PERSON PRIMARY KEY (ID),
    CONSTRAINT UK_PT_PERSON_EXTERNAL_ID UNIQUE (EXTERNAL_ID)
);

CREATE TABLE PT_PERSON_TAG (
    ID VARCHAR(32) NOT NULL,
    PERSON_ID VARCHAR(32) NOT NULL,
    TAG_ID VARCHAR(32) NOT NULL,
    SOURCE_TYPE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    RULE_ID VARCHAR(32),
    BATCH_NO VARCHAR(100),
    MATCHED_KEYWORD VARCHAR(200),
    REVIEWED_BY VARCHAR(100),
    REVIEWED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_PERSON_TAG PRIMARY KEY (ID),
    CONSTRAINT FK_PT_PERSON_TAG_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PT_PERSON(ID),
    CONSTRAINT FK_PT_PERSON_TAG_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_PT_PERSON_TAG UNIQUE (PERSON_ID, TAG_ID)
);

CREATE TABLE PT_SYNC_BATCH (
    ID VARCHAR(32) NOT NULL,
    BATCH_NO VARCHAR(100) NOT NULL,
    SYNC_TYPE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CURSOR_BEFORE VARCHAR(500),
    CURSOR_AFTER VARCHAR(500),
    RECEIVED_COUNT INT DEFAULT 0 NOT NULL,
    SUCCESS_COUNT INT DEFAULT 0 NOT NULL,
    FAILURE_COUNT INT DEFAULT 0 NOT NULL,
    ERROR_MESSAGE VARCHAR(1000),
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    CONSTRAINT PK_PT_SYNC_BATCH PRIMARY KEY (ID),
    CONSTRAINT UK_PT_SYNC_BATCH_NO UNIQUE (BATCH_NO)
);

CREATE TABLE PT_SYNC_STATE (
    TASK_CODE VARCHAR(64) NOT NULL,
    LAST_CURSOR VARCHAR(500),
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_SYNC_STATE PRIMARY KEY (TASK_CODE)
);

CREATE INDEX IDX_PT_RULE_TAG_STATUS ON PT_TAG_RULE(TAG_ID, STATUS);
CREATE INDEX IDX_PT_PERSON_NAME ON PT_PERSON(NAME);
CREATE INDEX IDX_PT_PERSON_TAG_TAG ON PT_PERSON_TAG(TAG_ID, STATUS, PERSON_ID);
CREATE INDEX IDX_PT_PERSON_TAG_PERSON ON PT_PERSON_TAG(PERSON_ID, STATUS);
CREATE INDEX IDX_PT_BATCH_STATUS ON PT_SYNC_BATCH(STATUS, STARTED_AT);

INSERT INTO PT_SYNC_STATE(TASK_CODE, LAST_CURSOR, UPDATED_AT)
VALUES ('PERSON_INCREMENTAL', NULL, CURRENT_TIMESTAMP);

