-- 人员动态指标、结构化规则、规则证据和批次。必须在 V1 之后执行。

CREATE TABLE PT_INDICATOR_DEFINITION (
    ID VARCHAR(32) NOT NULL,
    CODE VARCHAR(64) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DATA_TYPE VARCHAR(20) NOT NULL,
    SOURCE_TYPE VARCHAR(20) NOT NULL,
    PERSON_FIELD VARCHAR(64),
    UNIT VARCHAR(30),
    STATUS INT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_INDICATOR_DEF PRIMARY KEY (ID),
    CONSTRAINT UK_PT_INDICATOR_DEF_CODE UNIQUE (CODE)
);

COMMENT ON TABLE PT_INDICATOR_DEFINITION IS '人员可计算指标定义表';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.ID IS '指标主键，32位UUID';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.CODE IS '不可修改的指标编码';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.NAME IS '指标显示名称';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.DATA_TYPE IS '数据类型：TEXT、NUMBER、DATE、DATETIME、BOOLEAN、ENUM';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.SOURCE_TYPE IS '数据来源：PERSON_FIELD、IMPORT、REMOTE、DERIVED';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.PERSON_FIELD IS 'PERSON_FIELD来源对应的安全字段编码';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.UNIT IS '数字指标单位';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.STATUS IS '启用状态：1启用，0停用';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_INDICATOR_DEFINITION.UPDATED_AT IS '更新时间';

CREATE TABLE PT_INDICATOR_OPTION (
    ID VARCHAR(32) NOT NULL,
    INDICATOR_ID VARCHAR(32) NOT NULL,
    OPTION_CODE VARCHAR(100) NOT NULL,
    OPTION_LABEL VARCHAR(100) NOT NULL,
    SORT_NO INT DEFAULT 0 NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_INDICATOR_OPTION PRIMARY KEY (ID),
    CONSTRAINT FK_PT_OPTION_INDICATOR FOREIGN KEY (INDICATOR_ID) REFERENCES PT_INDICATOR_DEFINITION(ID),
    CONSTRAINT UK_PT_INDICATOR_OPTION UNIQUE (INDICATOR_ID, OPTION_CODE)
);

COMMENT ON TABLE PT_INDICATOR_OPTION IS '枚举指标可选项表';
COMMENT ON COLUMN PT_INDICATOR_OPTION.ID IS '选项主键，32位UUID';
COMMENT ON COLUMN PT_INDICATOR_OPTION.INDICATOR_ID IS '关联指标主键';
COMMENT ON COLUMN PT_INDICATOR_OPTION.OPTION_CODE IS '不可修改的选项编码';
COMMENT ON COLUMN PT_INDICATOR_OPTION.OPTION_LABEL IS '选项显示名称';
COMMENT ON COLUMN PT_INDICATOR_OPTION.SORT_NO IS '显示顺序';
COMMENT ON COLUMN PT_INDICATOR_OPTION.STATUS IS '启用状态：1启用，0停用';
COMMENT ON COLUMN PT_INDICATOR_OPTION.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_INDICATOR_OPTION.UPDATED_AT IS '更新时间';

CREATE TABLE PT_PERSON_INDICATOR (
    ID VARCHAR(32) NOT NULL,
    PERSON_ID VARCHAR(32) NOT NULL,
    INDICATOR_ID VARCHAR(32) NOT NULL,
    STRING_VALUE VARCHAR(1000),
    NUMBER_VALUE DECIMAL(28,6),
    DATE_VALUE TIMESTAMP,
    BOOLEAN_VALUE INT,
    OPTION_CODE VARCHAR(100),
    PERIOD_START TIMESTAMP,
    PERIOD_END TIMESTAMP,
    SOURCE_TYPE VARCHAR(20) NOT NULL,
    IMPORT_BATCH_NO VARCHAR(100),
    SOURCE_UPDATED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_PERSON_INDICATOR PRIMARY KEY (ID),
    CONSTRAINT FK_PT_VALUE_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PT_PERSON(ID),
    CONSTRAINT FK_PT_VALUE_INDICATOR FOREIGN KEY (INDICATOR_ID) REFERENCES PT_INDICATOR_DEFINITION(ID),
    CONSTRAINT UK_PT_PERSON_INDICATOR UNIQUE (PERSON_ID, INDICATOR_ID)
);

COMMENT ON TABLE PT_PERSON_INDICATOR IS '人员当前指标快照表';
COMMENT ON COLUMN PT_PERSON_INDICATOR.ID IS '人员指标主键，32位UUID';
COMMENT ON COLUMN PT_PERSON_INDICATOR.PERSON_ID IS '关联人员主键';
COMMENT ON COLUMN PT_PERSON_INDICATOR.INDICATOR_ID IS '关联指标主键';
COMMENT ON COLUMN PT_PERSON_INDICATOR.STRING_VALUE IS '文本类型值';
COMMENT ON COLUMN PT_PERSON_INDICATOR.NUMBER_VALUE IS '数字类型值';
COMMENT ON COLUMN PT_PERSON_INDICATOR.DATE_VALUE IS '日期或时间类型值';
COMMENT ON COLUMN PT_PERSON_INDICATOR.BOOLEAN_VALUE IS '布尔类型值：1真，0假';
COMMENT ON COLUMN PT_PERSON_INDICATOR.OPTION_CODE IS '枚举类型选项编码';
COMMENT ON COLUMN PT_PERSON_INDICATOR.PERIOD_START IS '指标统计周期开始时间';
COMMENT ON COLUMN PT_PERSON_INDICATOR.PERIOD_END IS '指标统计周期结束时间';
COMMENT ON COLUMN PT_PERSON_INDICATOR.SOURCE_TYPE IS '本次值来源：IMPORT、REMOTE、DERIVED';
COMMENT ON COLUMN PT_PERSON_INDICATOR.IMPORT_BATCH_NO IS 'Excel导入批次号';
COMMENT ON COLUMN PT_PERSON_INDICATOR.SOURCE_UPDATED_AT IS '来源数据更新时间';
COMMENT ON COLUMN PT_PERSON_INDICATOR.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_PERSON_INDICATOR.UPDATED_AT IS '更新时间';

CREATE TABLE PT_TAG_RULE_SET (
    ID VARCHAR(32) NOT NULL,
    TAG_ID VARCHAR(32) NOT NULL,
    VERSION_NO INT NOT NULL,
    MATCH_MODE VARCHAR(10) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    PUBLISHED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_TAG_RULE_SET PRIMARY KEY (ID),
    CONSTRAINT FK_PT_RULE_SET_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_PT_TAG_RULE_VERSION UNIQUE (TAG_ID, VERSION_NO)
);

COMMENT ON TABLE PT_TAG_RULE_SET IS '标签结构化规则集及版本表';
COMMENT ON COLUMN PT_TAG_RULE_SET.ID IS '规则集主键，32位UUID';
COMMENT ON COLUMN PT_TAG_RULE_SET.TAG_ID IS '规则最终产生的标签主键';
COMMENT ON COLUMN PT_TAG_RULE_SET.VERSION_NO IS '同一标签下递增的规则版本';
COMMENT ON COLUMN PT_TAG_RULE_SET.MATCH_MODE IS '条件关系：ALL全部满足、ANY满足任一';
COMMENT ON COLUMN PT_TAG_RULE_SET.STATUS IS '规则状态：DRAFT草稿、PUBLISHED已发布、DISABLED已停用';
COMMENT ON COLUMN PT_TAG_RULE_SET.PUBLISHED_AT IS '发布时间';
COMMENT ON COLUMN PT_TAG_RULE_SET.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_TAG_RULE_SET.UPDATED_AT IS '更新时间';

CREATE TABLE PT_TAG_RULE_CONDITION (
    ID VARCHAR(32) NOT NULL,
    RULE_SET_ID VARCHAR(32) NOT NULL,
    INDICATOR_ID VARCHAR(32) NOT NULL,
    OPERATOR_CODE VARCHAR(30) NOT NULL,
    EXPECTED_VALUES VARCHAR(2000),
    SORT_NO INT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_RULE_CONDITION PRIMARY KEY (ID),
    CONSTRAINT FK_PT_CONDITION_RULE_SET FOREIGN KEY (RULE_SET_ID) REFERENCES PT_TAG_RULE_SET(ID),
    CONSTRAINT FK_PT_CONDITION_INDICATOR FOREIGN KEY (INDICATOR_ID) REFERENCES PT_INDICATOR_DEFINITION(ID)
);

COMMENT ON TABLE PT_TAG_RULE_CONDITION IS '结构化规则条件表';
COMMENT ON COLUMN PT_TAG_RULE_CONDITION.ID IS '规则条件主键，32位UUID';
COMMENT ON COLUMN PT_TAG_RULE_CONDITION.RULE_SET_ID IS '关联规则集主键';
COMMENT ON COLUMN PT_TAG_RULE_CONDITION.INDICATOR_ID IS '被比较的人员指标主键';
COMMENT ON COLUMN PT_TAG_RULE_CONDITION.OPERATOR_CODE IS '安全运算符编码';
COMMENT ON COLUMN PT_TAG_RULE_CONDITION.EXPECTED_VALUES IS 'JSON数组格式的类型化比较参数';
COMMENT ON COLUMN PT_TAG_RULE_CONDITION.SORT_NO IS '条件显示和执行顺序';
COMMENT ON COLUMN PT_TAG_RULE_CONDITION.CREATED_AT IS '创建时间';

CREATE TABLE PT_RULE_EVAL_BATCH (
    ID VARCHAR(32) NOT NULL,
    BATCH_NO VARCHAR(100) NOT NULL,
    RULE_SET_ID VARCHAR(32) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    SCANNED_COUNT INT DEFAULT 0 NOT NULL,
    MATCHED_COUNT INT DEFAULT 0 NOT NULL,
    EXPIRED_COUNT INT DEFAULT 0 NOT NULL,
    ERROR_MESSAGE VARCHAR(1000),
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    CONSTRAINT PK_PT_RULE_EVAL_BATCH PRIMARY KEY (ID),
    CONSTRAINT UK_PT_RULE_EVAL_BATCH UNIQUE (BATCH_NO),
    CONSTRAINT FK_PT_EVAL_RULE_SET FOREIGN KEY (RULE_SET_ID) REFERENCES PT_TAG_RULE_SET(ID)
);

COMMENT ON TABLE PT_RULE_EVAL_BATCH IS '结构化规则重算批次表';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.ID IS '重算批次主键，32位UUID';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.BATCH_NO IS '重算幂等批次号';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.RULE_SET_ID IS '本次计算的规则集主键';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.STATUS IS '批次状态：RUNNING、SUCCESS、FAILED';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.SCANNED_COUNT IS '扫描人员数';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.MATCHED_COUNT IS '命中人员数';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.EXPIRED_COUNT IS '本次失效证据数';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.ERROR_MESSAGE IS '失败原因';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.STARTED_AT IS '开始时间';
COMMENT ON COLUMN PT_RULE_EVAL_BATCH.FINISHED_AT IS '结束时间';

CREATE TABLE PT_PERSON_TAG_EVIDENCE (
    ID VARCHAR(32) NOT NULL,
    PERSON_ID VARCHAR(32) NOT NULL,
    TAG_ID VARCHAR(32) NOT NULL,
    SOURCE_TYPE VARCHAR(20) NOT NULL,
    RULE_SET_ID VARCHAR(32),
    RULE_VERSION INT,
    BATCH_NO VARCHAR(100),
    MATCH_DETAIL VARCHAR(2000),
    EVIDENCE_STATUS VARCHAR(20) NOT NULL,
    REVIEW_STATUS VARCHAR(20) NOT NULL,
    REVIEWED_BY VARCHAR(100),
    REVIEWED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_PT_TAG_EVIDENCE PRIMARY KEY (ID),
    CONSTRAINT FK_PT_EVIDENCE_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PT_PERSON(ID),
    CONSTRAINT FK_PT_EVIDENCE_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT FK_PT_EVIDENCE_RULE_SET FOREIGN KEY (RULE_SET_ID) REFERENCES PT_TAG_RULE_SET(ID),
    CONSTRAINT UK_PT_RULE_EVIDENCE UNIQUE (PERSON_ID, TAG_ID, RULE_SET_ID, RULE_VERSION)
);

COMMENT ON TABLE PT_PERSON_TAG_EVIDENCE IS '人员标签多来源命中证据表';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.ID IS '证据主键，32位UUID';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.PERSON_ID IS '关联人员主键';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.TAG_ID IS '关联标签主键';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.SOURCE_TYPE IS '证据来源：MANUAL、REMOTE、RULE';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.RULE_SET_ID IS '命中的结构化规则集主键';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.RULE_VERSION IS '命中的规则版本';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.BATCH_NO IS '产生证据的计算批次号';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.MATCH_DETAIL IS 'JSON格式的实际命中字段和值';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.EVIDENCE_STATUS IS '证据状态：ACTIVE有效、EXPIRED失效';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.REVIEW_STATUS IS '审核状态：PENDING、APPROVED、REJECTED';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.REVIEWED_BY IS '审核人';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.REVIEWED_AT IS '审核时间';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PT_PERSON_TAG_EVIDENCE.UPDATED_AT IS '更新时间';

CREATE TABLE PT_IMPORT_BATCH (
    ID VARCHAR(32) NOT NULL,
    BATCH_NO VARCHAR(100) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    TOTAL_COUNT INT DEFAULT 0 NOT NULL,
    SUCCESS_COUNT INT DEFAULT 0 NOT NULL,
    ERROR_MESSAGE VARCHAR(2000),
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    CONSTRAINT PK_PT_IMPORT_BATCH PRIMARY KEY (ID),
    CONSTRAINT UK_PT_IMPORT_BATCH UNIQUE (BATCH_NO)
);

COMMENT ON TABLE PT_IMPORT_BATCH IS '人员Excel整批导入记录表';
COMMENT ON COLUMN PT_IMPORT_BATCH.ID IS '导入批次主键，32位UUID';
COMMENT ON COLUMN PT_IMPORT_BATCH.BATCH_NO IS '导入幂等批次号';
COMMENT ON COLUMN PT_IMPORT_BATCH.FILE_NAME IS '原始文件名';
COMMENT ON COLUMN PT_IMPORT_BATCH.STATUS IS '导入状态：RUNNING、SUCCESS、FAILED';
COMMENT ON COLUMN PT_IMPORT_BATCH.TOTAL_COUNT IS '文件数据行数';
COMMENT ON COLUMN PT_IMPORT_BATCH.SUCCESS_COUNT IS '成功写入人员数';
COMMENT ON COLUMN PT_IMPORT_BATCH.ERROR_MESSAGE IS '整批校验或写入错误';
COMMENT ON COLUMN PT_IMPORT_BATCH.STARTED_AT IS '开始时间';
COMMENT ON COLUMN PT_IMPORT_BATCH.FINISHED_AT IS '结束时间';

CREATE INDEX IDX_PT_INDICATOR_STATUS ON PT_INDICATOR_DEFINITION(STATUS, CODE);
CREATE INDEX IDX_PT_PERSON_VALUE_NUMBER ON PT_PERSON_INDICATOR(INDICATOR_ID, NUMBER_VALUE, PERSON_ID);
CREATE INDEX IDX_PT_PERSON_VALUE_DATE ON PT_PERSON_INDICATOR(INDICATOR_ID, DATE_VALUE, PERSON_ID);
CREATE INDEX IDX_PT_PERSON_VALUE_OPTION ON PT_PERSON_INDICATOR(INDICATOR_ID, OPTION_CODE, PERSON_ID);
CREATE INDEX IDX_PT_RULE_SET_TAG_STATUS ON PT_TAG_RULE_SET(TAG_ID, STATUS, VERSION_NO);
CREATE INDEX IDX_PT_EVIDENCE_TAG_STATUS ON PT_PERSON_TAG_EVIDENCE(TAG_ID, EVIDENCE_STATUS, REVIEW_STATUS, PERSON_ID);

INSERT INTO PT_INDICATOR_DEFINITION
(ID, CODE, NAME, DATA_TYPE, SOURCE_TYPE, PERSON_FIELD, UNIT, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('30000000000000000000000000000001', 'GENDER', '性别', 'ENUM', 'PERSON_FIELD', 'gender', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PT_INDICATOR_DEFINITION
(ID, CODE, NAME, DATA_TYPE, SOURCE_TYPE, PERSON_FIELD, UNIT, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('30000000000000000000000000000002', 'ORGANIZATION', '所属机构', 'TEXT', 'PERSON_FIELD', 'organization', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PT_INDICATOR_DEFINITION
(ID, CODE, NAME, DATA_TYPE, SOURCE_TYPE, PERSON_FIELD, UNIT, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('30000000000000000000000000000003', 'OCCUPATION', '职业', 'TEXT', 'PERSON_FIELD', 'occupation', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PT_INDICATOR_DEFINITION
(ID, CODE, NAME, DATA_TYPE, SOURCE_TYPE, PERSON_FIELD, UNIT, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('30000000000000000000000000000004', 'ADDRESS', '地区或地址', 'TEXT', 'PERSON_FIELD', 'address', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PT_INDICATOR_DEFINITION
(ID, CODE, NAME, DATA_TYPE, SOURCE_TYPE, PERSON_FIELD, UNIT, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('30000000000000000000000000000005', 'REMARK', '备注', 'TEXT', 'PERSON_FIELD', 'remark', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PT_INDICATOR_OPTION
(ID, INDICATOR_ID, OPTION_CODE, OPTION_LABEL, SORT_NO, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('31000000000000000000000000000001', '30000000000000000000000000000001', '男', '男', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PT_INDICATOR_OPTION
(ID, INDICATOR_ID, OPTION_CODE, OPTION_LABEL, SORT_NO, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('31000000000000000000000000000002', '30000000000000000000000000000001', '女', '女', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PT_INDICATOR_OPTION
(ID, INDICATOR_ID, OPTION_CODE, OPTION_LABEL, SORT_NO, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('31000000000000000000000000000003', '30000000000000000000000000000001', '未知', '未知', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
