DROP TABLE IF EXISTS PT_IMPORT_BATCH;
DROP TABLE IF EXISTS PT_PERSON_TAG_EVIDENCE;
DROP TABLE IF EXISTS PT_RULE_EVAL_BATCH;
DROP TABLE IF EXISTS PT_TAG_RULE_CONDITION;
DROP TABLE IF EXISTS PT_TAG_RULE_SET;
DROP TABLE IF EXISTS PT_PERSON_INDICATOR;
DROP TABLE IF EXISTS PT_INDICATOR_OPTION;
DROP TABLE IF EXISTS PT_INDICATOR_DEFINITION;
DROP TABLE IF EXISTS PT_PERSON_TAG;
DROP TABLE IF EXISTS PT_TAG_RULE;
DROP TABLE IF EXISTS PT_SYNC_BATCH;
DROP TABLE IF EXISTS PT_SYNC_STATE;
DROP TABLE IF EXISTS PT_PERSON;
DROP TABLE IF EXISTS PT_TAG_DEFINITION;

CREATE TABLE PT_TAG_DEFINITION (
    ID VARCHAR(32) PRIMARY KEY, CODE VARCHAR(64) NOT NULL UNIQUE, NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL, DESCRIPTION VARCHAR(500), STATUS INT NOT NULL,
    AUTO_APPROVE INT NOT NULL, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL
);
CREATE TABLE PT_TAG_RULE (
    ID VARCHAR(32) PRIMARY KEY, TAG_ID VARCHAR(32) NOT NULL, KEYWORD VARCHAR(200) NOT NULL,
    NORMALIZED_KEYWORD VARCHAR(200) NOT NULL, STATUS INT NOT NULL, VERSION_NO INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_RULE_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_RULE_WORD UNIQUE (TAG_ID, NORMALIZED_KEYWORD)
);
CREATE TABLE PT_PERSON (
    ID VARCHAR(32) PRIMARY KEY, EXTERNAL_ID VARCHAR(100) NOT NULL UNIQUE, NAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(20), ORGANIZATION VARCHAR(200), OCCUPATION VARCHAR(200), ADDRESS VARCHAR(500),
    REMARK VARCHAR(1000), SOURCE_UPDATED_AT TIMESTAMP, DELETED_FLAG INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL
);
CREATE TABLE PT_PERSON_TAG (
    ID VARCHAR(32) PRIMARY KEY, PERSON_ID VARCHAR(32) NOT NULL, TAG_ID VARCHAR(32) NOT NULL,
    SOURCE_TYPE VARCHAR(20) NOT NULL, SOURCE_REF VARCHAR(100) NOT NULL, STATUS VARCHAR(20) NOT NULL, RULE_ID VARCHAR(32),
    BATCH_NO VARCHAR(100), MATCHED_KEYWORD VARCHAR(200), REVIEWED_BY VARCHAR(100),
    REVIEWED_AT TIMESTAMP, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_BIND_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PT_PERSON(ID),
    CONSTRAINT FK_BIND_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_PERSON_TAG_SOURCE UNIQUE (PERSON_ID, TAG_ID, SOURCE_TYPE, SOURCE_REF)
);
CREATE TABLE PT_SYNC_BATCH (
    ID VARCHAR(32) PRIMARY KEY, BATCH_NO VARCHAR(100) NOT NULL UNIQUE, SYNC_TYPE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(20) NOT NULL, CURSOR_BEFORE VARCHAR(500), CURSOR_AFTER VARCHAR(500),
    RECEIVED_COUNT INT NOT NULL, SUCCESS_COUNT INT NOT NULL, FAILURE_COUNT INT NOT NULL,
    ERROR_MESSAGE VARCHAR(1000), STARTED_AT TIMESTAMP NOT NULL, FINISHED_AT TIMESTAMP
);
CREATE TABLE PT_SYNC_STATE (
    TASK_CODE VARCHAR(64) PRIMARY KEY, LAST_CURSOR VARCHAR(500), UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE PT_INDICATOR_DEFINITION (
    ID VARCHAR(32) PRIMARY KEY, CODE VARCHAR(64) NOT NULL UNIQUE, NAME VARCHAR(100) NOT NULL,
    DATA_TYPE VARCHAR(20) NOT NULL, SOURCE_TYPE VARCHAR(20) NOT NULL, PERSON_FIELD VARCHAR(64),
    UNIT VARCHAR(30), STATUS INT NOT NULL, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL
);
CREATE TABLE PT_INDICATOR_OPTION (
    ID VARCHAR(32) PRIMARY KEY, INDICATOR_ID VARCHAR(32) NOT NULL, OPTION_CODE VARCHAR(100) NOT NULL,
    OPTION_LABEL VARCHAR(100) NOT NULL, SORT_NO INT NOT NULL, STATUS INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_OPTION_IND FOREIGN KEY (INDICATOR_ID) REFERENCES PT_INDICATOR_DEFINITION(ID),
    CONSTRAINT UK_IND_OPTION UNIQUE (INDICATOR_ID, OPTION_CODE)
);
CREATE TABLE PT_PERSON_INDICATOR (
    ID VARCHAR(32) PRIMARY KEY, PERSON_ID VARCHAR(32) NOT NULL, INDICATOR_ID VARCHAR(32) NOT NULL,
    STRING_VALUE VARCHAR(1000), NUMBER_VALUE DECIMAL(28,6), DATE_VALUE TIMESTAMP, BOOLEAN_VALUE INT,
    OPTION_CODE VARCHAR(100), PERIOD_START TIMESTAMP, PERIOD_END TIMESTAMP, SOURCE_TYPE VARCHAR(20) NOT NULL,
    IMPORT_BATCH_NO VARCHAR(100), SOURCE_UPDATED_AT TIMESTAMP, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_PIV_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PT_PERSON(ID),
    CONSTRAINT FK_PIV_IND FOREIGN KEY (INDICATOR_ID) REFERENCES PT_INDICATOR_DEFINITION(ID),
    CONSTRAINT UK_PIV UNIQUE (PERSON_ID, INDICATOR_ID)
);
CREATE TABLE PT_TAG_RULE_SET (
    ID VARCHAR(32) PRIMARY KEY, TAG_ID VARCHAR(32) NOT NULL, VERSION_NO INT NOT NULL,
    MATCH_MODE VARCHAR(10) NOT NULL, STATUS VARCHAR(20) NOT NULL, PUBLISHED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_RULESET_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_RULESET_VERSION UNIQUE (TAG_ID, VERSION_NO)
);
CREATE TABLE PT_TAG_RULE_CONDITION (
    ID VARCHAR(32) PRIMARY KEY, RULE_SET_ID VARCHAR(32) NOT NULL, INDICATOR_ID VARCHAR(32) NOT NULL,
    OPERATOR_CODE VARCHAR(30) NOT NULL, EXPECTED_VALUES VARCHAR(2000), SORT_NO INT NOT NULL, CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_COND_RULESET FOREIGN KEY (RULE_SET_ID) REFERENCES PT_TAG_RULE_SET(ID),
    CONSTRAINT FK_COND_IND FOREIGN KEY (INDICATOR_ID) REFERENCES PT_INDICATOR_DEFINITION(ID)
);
CREATE TABLE PT_RULE_EVAL_BATCH (
    ID VARCHAR(32) PRIMARY KEY, BATCH_NO VARCHAR(100) NOT NULL UNIQUE, RULE_SET_ID VARCHAR(32) NOT NULL,
    STATUS VARCHAR(20) NOT NULL, SCANNED_COUNT INT NOT NULL, MATCHED_COUNT INT NOT NULL,
    EXPIRED_COUNT INT NOT NULL, ERROR_MESSAGE VARCHAR(1000), STARTED_AT TIMESTAMP NOT NULL, FINISHED_AT TIMESTAMP,
    CONSTRAINT FK_EVAL_RULESET FOREIGN KEY (RULE_SET_ID) REFERENCES PT_TAG_RULE_SET(ID)
);
CREATE TABLE PT_PERSON_TAG_EVIDENCE (
    ID VARCHAR(32) PRIMARY KEY, PERSON_ID VARCHAR(32) NOT NULL, TAG_ID VARCHAR(32) NOT NULL,
    SOURCE_TYPE VARCHAR(20) NOT NULL, RULE_SET_ID VARCHAR(32), RULE_VERSION INT, BATCH_NO VARCHAR(100),
    MATCH_DETAIL VARCHAR(2000), EVIDENCE_STATUS VARCHAR(20) NOT NULL, REVIEW_STATUS VARCHAR(20) NOT NULL,
    REVIEWED_BY VARCHAR(100), REVIEWED_AT TIMESTAMP, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_EV_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PT_PERSON(ID),
    CONSTRAINT FK_EV_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT FK_EV_RULESET FOREIGN KEY (RULE_SET_ID) REFERENCES PT_TAG_RULE_SET(ID),
    CONSTRAINT UK_RULE_EVIDENCE UNIQUE (PERSON_ID, TAG_ID, RULE_SET_ID, RULE_VERSION)
);
CREATE TABLE PT_IMPORT_BATCH (
    ID VARCHAR(32) PRIMARY KEY, BATCH_NO VARCHAR(100) NOT NULL UNIQUE, FILE_NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) NOT NULL, TOTAL_COUNT INT NOT NULL, SUCCESS_COUNT INT NOT NULL,
    ERROR_MESSAGE VARCHAR(2000), STARTED_AT TIMESTAMP NOT NULL, FINISHED_AT TIMESTAMP
);
