DROP TABLE IF EXISTS PT_PERSON_TAG;
DROP TABLE IF EXISTS PT_TAG_RULE;
DROP TABLE IF EXISTS PT_SYNC_BATCH;
DROP TABLE IF EXISTS PT_SYNC_STATE;
DROP TABLE IF EXISTS PT_PERSON;
DROP TABLE IF EXISTS PT_TAG_DEFINITION;

CREATE TABLE PT_TAG_DEFINITION (
    ID VARCHAR(32) PRIMARY KEY, CODE VARCHAR(64) NOT NULL UNIQUE, NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL, DESCRIPTION VARCHAR(500), STATUS INT NOT NULL,
    AUTO_APPROVE INT NOT NULL, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL
);
CREATE TABLE PT_TAG_RULE (
    ID VARCHAR(32) PRIMARY KEY, TAG_ID VARCHAR(32) NOT NULL, KEYWORD VARCHAR(200) NOT NULL,
    NORMALIZED_KEYWORD VARCHAR(200) NOT NULL, STATUS INT NOT NULL, VERSION_NO INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_RULE_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_RULE_WORD UNIQUE (TAG_ID, NORMALIZED_KEYWORD)
);
CREATE TABLE PT_PERSON (
    ID VARCHAR(32) PRIMARY KEY, EXTERNAL_ID VARCHAR(100) NOT NULL UNIQUE, NAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(20), ORGANIZATION VARCHAR(200), OCCUPATION VARCHAR(200), ADDRESS VARCHAR(500),
    REMARK VARCHAR(1000), SOURCE_UPDATED_AT TIMESTAMP, DELETED_FLAG INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL
);
CREATE TABLE PT_PERSON_TAG (
    ID VARCHAR(32) PRIMARY KEY, PERSON_ID VARCHAR(32) NOT NULL, TAG_ID VARCHAR(32) NOT NULL,
    SOURCE_TYPE VARCHAR(20) NOT NULL, STATUS VARCHAR(20) NOT NULL, RULE_ID VARCHAR(32),
    BATCH_NO VARCHAR(100), MATCHED_KEYWORD VARCHAR(200), REVIEWED_BY VARCHAR(100),
    REVIEWED_AT TIMESTAMP, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_BIND_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PT_PERSON(ID),
    CONSTRAINT FK_BIND_TAG FOREIGN KEY (TAG_ID) REFERENCES PT_TAG_DEFINITION(ID),
    CONSTRAINT UK_PERSON_TAG UNIQUE (PERSON_ID, TAG_ID)
);
CREATE TABLE PT_SYNC_BATCH (
    ID VARCHAR(32) PRIMARY KEY, BATCH_NO VARCHAR(100) NOT NULL UNIQUE, SYNC_TYPE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(20) NOT NULL, CURSOR_BEFORE VARCHAR(500), CURSOR_AFTER VARCHAR(500),
    RECEIVED_COUNT INT NOT NULL, SUCCESS_COUNT INT NOT NULL, FAILURE_COUNT INT NOT NULL,
    ERROR_MESSAGE VARCHAR(1000), STARTED_AT TIMESTAMP NOT NULL, FINISHED_AT TIMESTAMP
);
CREATE TABLE PT_SYNC_STATE (
    TASK_CODE VARCHAR(64) PRIMARY KEY, LAST_CURSOR VARCHAR(500), UPDATED_AT TIMESTAMP NOT NULL
);

